name: angel
description: An easily-extensible web server framework in Dart.
version: 1.0.0-dev
author: Tobe O
homepage: https://github.com/angel-dart/angel
publish_to: none
dependencies:
  angel_common: ^1.0.0-alpha
  angel_configuration: ^1.0.0-dev
  angular2: ^2.0.0
  angular2_components: ^0.2.2
  dart_to_js_script_rewriter: ^1.0.0
  mailer: ^1.1.0+4
  material_menu: ^1.0.0
  material_sidenav: ^1.0.0
  material_toolbar: ^1.0.0
dev_dependencies:
  http: ^0.11.3
  grinder: ^0.8.0+2
  test: ^0.12.13
transformers:
- angel_configuration
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
