# Default server configuration.
db:
  migrate:
    database: angel
    username: root
    password: password
  web:
    database: angel
    username: username
    password: password
host: 127.0.0.1
mongo_db: mongodb://localhost:27017/gallery
port: 3000
upload_path: web/uploads